#creating blocks
block1= drawRect(100,board.gap-50,240, board.border_width,board.red)
board.allSprites.add(block1)
board.allBlocks.add(block1)
block2 = drawRect(10,1.5*board.gap,400, board.border_width,board.red)
board.allSprites.add(block2)
board.allBlocks.add(block2)
block3 = drawRect(180,2.5*board.gap,450, board.border_width,board.red)
board.allSprites.add(block3)
board.allBlocks.add(block3)
block4 = drawRect(10,3.5*board.gap,480, board.border_width,board.red)
board.allSprites.add(block4)
board.allBlocks.add(block4)
block5 = drawRect(150,4.5*board.gap,480, board.border_width,board.red)
board.allSprites.add(block5)
board.allBlocks.add(block5)
block6 = drawRect(10,5.5*board.gap,450, board.border_width,board.red)
board.allSprites.add(block6)
board.allBlocks.add(block6)

#princess blocks
block7 = drawRect(100,board.border_width,board.border_width,50,board.red)
board.allSprites.add(block7)
board.allSides.add(block7)
block8 = drawRect(340,board.border_width,board.border_width,50,board.red)
board.allSprites.add(block8)
board.allSides.add(block8)
